[nushell]
src.git = "https://github.com/cognitive-singularity/nushell"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/nushell"

[nu_scripts]
src.git = "https://github.com/cognitive-singularity/nu_scripts"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/nu_scripts"

[terminusdb]
src.git = "https://github.com/cognitive-singularity/terminusdb"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/terminusdb"

[terminusdb-tus]
src.git = "https://github.com/cognitive-singularity/terminusdb-tus"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/terminusdb-tus"

[terminusdb-semantic-indexer]
src.git = "https://github.com/cognitive-singularity/terminusdb-semantic-indexer"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/terminusdb-semantic-indexer"

[nu_plugin_from_parquet]
src.git = "https://github.com/cognitive-singularity/nu_plugin_from_parquet"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/nu_plugin_from_parquet"

[nu_plugin_json_path]
src.git = "https://github.com/cognitive-singularity/nu_plugin_json_path"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/nu_plugin_json_path"

[nu_plugin_regex]
src.git = "https://github.com/cognitive-singularity/nu_plugin_regex"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/nu_plugin_regex"

[tg-archive]
src.git = "https://github.com/cognitive-singularity/tg-archive"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/tg-archive"

[pywebscrapbook]
src.git = "https://github.com/cognitive-singularity/PyWebScrapBook"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/PyWebScrapBook"

[webscrapbook]
src.git = "https://github.com/cognitive-singularity/webscrapbook"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/webscrapbook"

[isdcac]
src.git = "https://github.com/cognitive-singularity/I-Still-Dont-Care-About-Cookies"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/I-Still-Dont-Care-About-Cookies"

[ublock]
src.git = "https://github.com/cognitive-singularity/uBlock"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/uBlock"

[uassets-master]
src.git = "https://github.com/uBlockOrigin/uAssets"
src.branch = "master"
fetch.github = "uBlockOrigin/uAssets"

[uassets-prod]
src.git = "https://github.com/uBlockOrigin/uAssets"
src.branch = "gh-pages"
fetch.github = "uBlockOrigin/uAssets"

[bypass-paywalls-chrome]
src.git = "https://github.com/cognitive-singularity/bypass-paywalls-chrome"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/bypass-paywalls-chrome"

[infy-scroll]
src.git = "https://github.com/cognitive-singularity/infy-scroll"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/infy-scroll"

[automa]
src.git = "https://github.com/cognitive-singularity/automa"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/automa"

[archiveweb-page]
src.git = "https://github.com/cognitive-singularity/archiveweb.page"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/archiveweb.page"

[singlefile-lite]
src.git = "https://github.com/cognitive-singularity/singlefile-lite"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/singlefile-lite"

[oled-chrome]
src.git = "https://github.com/cognitive-singularity/oled-chrome"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/oled-chrome"

[goscrape]
src.git = "https://github.com/cognitive-singularity/goscrape"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/goscrape"

[enso-appimage]
src.github = "enso-org/enso"
src.prefix = "v"
fetch.url = "https://github.com/enso-org/enso/releases/download/2023.2.1-nightly.2023.8.3/enso-linux-2023.2.1-nightly.2023.8.3.AppImage"

[enso-engine]
src.github = "enso-org/enso"
fetch.url = "https://github.com/enso-org/enso/releases/download/2023.2.1-nightly.2023.8.3/enso-bundle-2023.2.1-nightly.2023.8.3-linux-amd64.tar.gz"

[structurizr-cli]
src.github = "structurizr/cli"
src.prefix = "v"
fetch.url = "https://github.com/structurizr/cli/releases/download/v$ver/structurizr-cli-$ver.zip"

[shell_gpt]
src.git = "https://github.com/cognitive-singularity/shell_gpt"
src.branch = "cognitive-singularity"
fetch.github = "cognitive-singularity/shell_gpt"
