syntaxes:
    - https://git.sr.ht/~yotam/tree-sitter-smali
    - https://github.com/6cdh/tree-sitter-racket
    - https://github.com/6cdh/tree-sitter-scheme
    - https://github.com/abstractmachineslab/tree-sitter-sexp
    - https://github.com/azganoth/tree-sitter-lua
    - https://github.com/bonabeavis/tree-sitter-sparql
    - https://github.com/bonabeavis/tree-sitter-turtle
    - https://github.com/chimehq/swifttreesitter
    - https://github.com/decodetalkers/tree-sitter-meson
    - https://github.com/fallenangel97/tree-sitter-rego
    - https://github.com/flakebi/tree-sitter-llvm-mir
    - https://github.com/flakebi/tree-sitter-tablegen
    - https://github.com/fymyte/tree-sitter-rasi
    - https://github.com/himujjal/tree-sitter-svelte
    - https://github.com/hubro/tree-sitter-yang
    - https://github.com/isopod/tree-sitter-pascal
    - https://github.com/joakker/tree-sitter-json5
    - https://github.com/julian/tree-sitter-lean
    - https://github.com/mdeiml/tree-sitter-markdown
    - https://github.com/michahoffmann/tree-sitter-hcl
    - https://github.com/observeroftime/tree-sitter-gitattributes
    - https://github.com/powershell/tree-sitter-powershell
    - https://github.com/systemrdl/tree-sitter-systemrdl
    - https://github.com/usernobody14/tree-sitter-dart
    - https://github.com/whatsapp/tree-sitter-erlang
    - https://github.com/wilfred/tree-sitter-elisp
    - https://github.com/aheber/tree-sitter-sfapex
    - https://github.com/alemuller/tree-sitter-make
    - https://github.com/alemuller/tree-sitter-re2c
    - https://github.com/alemuller/tree-sitter-vhdl
    - https://github.com/alex-pinkus/tree-sitter-swift
    - https://github.com/amaanq/tree-sitter-capnp
    - https://github.com/amaanq/tree-sitter-smali
    - https://github.com/benwilliamgraham/tree-sitter-llvm
    - https://github.com/bkegley/tree-sitter-graphql
    - https://github.com/briot/tree-sitter-ada
    - https://github.com/calicoday/ruby-tree-sitter-ffi
    - https://github.com/camdencheek/tree-sitter-dockerfile
    - https://github.com/camdencheek/tree-sitter-go-mod
    - https://github.com/cstrahan/tree-sitter-nix
    - https://github.com/dhcmrlchtdj/tree-sitter-sqlite
    - https://github.com/duskmoon314/tree-sitter-thrift
    - https://github.com/elixir-lang/tree-sitter-elixir
    - https://github.com/elm-tooling/tree-sitter-elm
    - https://github.com/eno-lang/tree-sitter-eno
    - https://github.com/euclidianace/ltreesitter
    - https://github.com/flurie/tree-sitter-jq
    - https://github.com/fwcd/tree-sitter-kotlin
    - https://github.com/ganezdragon/tree-sitter-perl
    - https://github.com/gbprod/tree-sitter-twig
    - https://github.com/gdamore/tree-sitter-d
    - https://github.com/gleam-lang/tree-sitter-gleam
    - https://github.com/grahambates/tree-sitter-m68k
    - https://github.com/ikatyang/tree-sitter-markdown
    - https://github.com/ikatyang/tree-sitter-toml
    - https://github.com/ikatyang/tree-sitter-vue
    - https://github.com/ikatyang/tree-sitter-yaml
    - https://github.com/jiyee/tree-sitter-objc
    - https://github.com/latex-lsp/tree-sitter-latex
    - https://github.com/m-novikov/tree-sitter-sql
    - https://github.com/maxxnino/tree-sitter-zig
    - https://github.com/mehmetoguzderin/tree-sitter-wgsl
    - https://github.com/metio/tree-sitter-ssh-client-config
    - https://github.com/milisims/tree-sitter-org
    - https://github.com/mitchellh/tree-sitter-proto
    - https://github.com/nilshelmig/tree-sitter-sourcepawn
    - https://github.com/nvim-treesitter/tree-sitter-query
    - https://github.com/omertuc/tree-sitter-go-work
    - https://github.com/oxisto/kotlintree
    - https://github.com/r-lib/tree-sitter-r
    - https://github.com/ram02z/tree-sitter-fish
    - https://github.com/returntocorp/ocaml-tree-sitter-core
    - https://github.com/rolandwalker/tree-sitter-pgn
    - https://github.com/rydesun/tree-sitter-dot
    - https://github.com/serenadeai/java-tree-sitter
    - https://github.com/serenadeai/tree-sitter-scss
    - https://github.com/shunsambongi/tree-sitter-gitignore
    - https://github.com/siraben/tree-sitter-formula
    - https://github.com/slackhq/tree-sitter-hack
    - https://github.com/smacker/go-tree-sitter
    - https://github.com/sogaiu/tree-sitter-clojure
    - https://github.com/stadelmanma/tree-sitter-fortran
    - https://github.com/staysail/tree-sitter-meson
    - https://github.com/stsewd/tree-sitter-comment
    - https://github.com/stsewd/tree-sitter-rst
    - https://github.com/takegue/tree-sitter-sql-bigquery
    - https://github.com/thehamsta/tree-sitter-commonlisp
    - https://github.com/thehamsta/tree-sitter-cuda
    - https://github.com/thehamsta/tree-sitter-glsl
    - https://github.com/travonted/tree-sitter-fennel
    - https://github.com/traxys/tree-sitter-lalrpop
    - https://github.com/tree-sitter-perl/tree-sitter-perl
    - https://github.com/tree-sitter-perl/tree-sitter-pod
    - https://github.com/tree-sitter/haskell-tree-sitter
    - https://github.com/tree-sitter/node-tree-sitter
    - https://github.com/tree-sitter/py-tree-sitter
    - https://github.com/tree-sitter/ruby-tree-sitter
    - https://github.com/tree-sitter/tree-sitter-agda
    - https://github.com/tree-sitter/tree-sitter-bash
    - https://github.com/tree-sitter/tree-sitter-c
    - https://github.com/tree-sitter/tree-sitter-c-sharp
    - https://github.com/tree-sitter/tree-sitter-cpp
    - https://github.com/tree-sitter/tree-sitter-css
    - https://github.com/tree-sitter/tree-sitter-embedded-template
    - https://github.com/tree-sitter/tree-sitter-go
    - https://github.com/tree-sitter/tree-sitter-haskell
    - https://github.com/tree-sitter/tree-sitter-html
    - https://github.com/tree-sitter/tree-sitter-java
    - https://github.com/tree-sitter/tree-sitter-javascript
    - https://github.com/tree-sitter/tree-sitter-json
    - https://github.com/tree-sitter/tree-sitter-julia
    - https://github.com/tree-sitter/tree-sitter-ocaml
    - https://github.com/tree-sitter/tree-sitter-php
    - https://github.com/tree-sitter/tree-sitter-python
    - https://github.com/tree-sitter/tree-sitter-regex
    - https://github.com/tree-sitter/tree-sitter-ruby
    - https://github.com/tree-sitter/tree-sitter-rust
    - https://github.com/tree-sitter/tree-sitter-scala
    - https://github.com/tree-sitter/tree-sitter-typescript
    - https://github.com/tree-sitter/tree-sitter-verilog
    - https://github.com/uyha/tree-sitter-cmake
    - https://github.com/wasm-lsp/tree-sitter-wasm
    - https://github.com/yuja/tree-sitter-qmljs
    - https://github.com/zwpaper/tree-sitter-beancount
