# [auth-thu]
# src.github = "z4yx/GoAuthing"
# fetch.github = "z4yx/GoAuthing"
# [smartdns-china-list]
# src.git = "https://github.com/felixonmars/dnsmasq-china-list"
# fetch.github = "felixonmars/dnsmasq-china-list"
# git.fetchSubmodules = true
# src.branch = "babel-rtt"

# https://github.com/wgsl-analyzer/wgsl-analyzer

# https://github.com/cognitive-singularity/terminusdb
# https://github.com/cognitive-singularity/terminusdb-semantic-indexer
# https://github.com/cognitive-singularity/rust-bert
# https://github.com/cognitive-singularity/webscrapbook
# https://github.com/cognitive-singularity/k8sgpt
# https://github.com/cognitive-singularity/mods
# https://github.com/cognitive-singularity/automa
# https://github.com/cognitive-singularity/terminusdb-semantic-indexer
# https://github.com/cognitive-singularity/LocalAI
