# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lint-staged = {
    pname = "lint-staged";
    version = "5cead2d4c1fc79171f41dd269402a8ee46d442cc";
    src = fetchFromGitHub {
      owner = "okonet";
      repo = "lint-staged";
      rev = "5cead2d4c1fc79171f41dd269402a8ee46d442cc";
      fetchSubmodules = false;
      sha256 = "sha256-LZ7kEsM7HC79KkxiuFOwOCWH/lrvDALW8EqeeiyIRSE=";
    };
    date = "2023-07-14";
  };
  wgsl_analyzer = {
    pname = "wgsl_analyzer";
    version = "latest";
    src = fetchurl {
      url = "https://github.com/wgsl-analyzer/wgsl-analyzer/releases/latest/download/wgsl_analyzer-linux-x64";
      sha256 = "sha256-HvQfvfvXcgkfk3Ly47eam0PpaIOQaMEZp6dqVnQgrAY=";
    };
  };
}
