# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  archive-page = {
    pname = "archive-page";
    version = "94d15e94430ccc9ee4b96454cd357cf902a4d3fb";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "archiveweb.page";
      rev = "94d15e94430ccc9ee4b96454cd357cf902a4d3fb";
      fetchSubmodules = false;
      sha256 = "sha256-LF+x6TbQyZuUiM+Wx4wpPdDSuuqz0cG0MSJX73niXfI=";
    };
    date = "2023-07-26";
  };
  automa = {
    pname = "automa";
    version = "b2e20a7a50cf47ec8bd5903a7059ece74a6dd571";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "automa";
      rev = "b2e20a7a50cf47ec8bd5903a7059ece74a6dd571";
      fetchSubmodules = false;
      sha256 = "sha256-c9OlADjG/6LC/TQyToaq32bBN0JgKuCAnvBv/puKb2k=";
    };
    date = "2023-02-16";
  };
  bypass-paywall = {
    pname = "bypass-paywall";
    version = "97b84f09512bf0d589f2d6c64c30a039cbd6d8b5";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "bypass-paywalls-chrome";
      rev = "97b84f09512bf0d589f2d6c64c30a039cbd6d8b5";
      fetchSubmodules = false;
      sha256 = "sha256-nOxeB7ty6njHhhv3D8z2Kj+sG9JXTPIdi1OGWQI11ic=";
    };
    date = "2023-06-17";
  };
  goscrape = {
    pname = "goscrape";
    version = "570f891f14eb66177f4a70a83d06f8fc2481afc0";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "goscrape";
      rev = "570f891f14eb66177f4a70a83d06f8fc2481afc0";
      fetchSubmodules = false;
      sha256 = "sha256-tuYJot5YPkhvJpC6WYGRun3yc41A2JJCCUQjvDKN1oY=";
    };
    date = "2023-04-04";
  };
  infy-scroll = {
    pname = "infy-scroll";
    version = "965cf2bc681682fad9ed5736e3f8b8f9bd08ea85";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "infy-scroll";
      rev = "965cf2bc681682fad9ed5736e3f8b8f9bd08ea85";
      fetchSubmodules = false;
      sha256 = "sha256-Wok3H5CAwThA9UF1OguHbUkUMO/uJeSS+ZuIY/1W1fE=";
    };
    date = "2023-06-30";
  };
  isdcac = {
    pname = "isdcac";
    version = "88484fdc60a6bb5f0792f858203a588737351727";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "I-Still-Dont-Care-About-Cookies";
      rev = "88484fdc60a6bb5f0792f858203a588737351727";
      fetchSubmodules = false;
      sha256 = "sha256-IV4OkvxqHzlt9fOS1Ks+MpADUU0I5LvhxuV5V/LBK28=";
    };
    date = "2023-07-05";
  };
  nu_plugin_from_parquet = {
    pname = "nu_plugin_from_parquet";
    version = "d6140d00223616d6632ed01bf90b4aa88c0a75e3";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "nu_plugin_from_parquet";
      rev = "d6140d00223616d6632ed01bf90b4aa88c0a75e3";
      fetchSubmodules = false;
      sha256 = "sha256-3XDdBO4lZx3xwQJek9y4aEJl9geizLFhh0TgOwI+hBA=";
    };
    date = "2023-08-02";
  };
  nu_plugin_json_path = {
    pname = "nu_plugin_json_path";
    version = "1d603f804c03326b99c2ac9e7f9dc0ffa5c91565";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "nu_plugin_json_path";
      rev = "1d603f804c03326b99c2ac9e7f9dc0ffa5c91565";
      fetchSubmodules = false;
      sha256 = "sha256-d51BoPCUSAM+sQPD5eeybw3ZMChbGW467izpHSkBqrs=";
    };
    date = "2023-08-02";
  };
  nu_plugin_regex = {
    pname = "nu_plugin_regex";
    version = "aee2bd945f8141fa3be92f34ff1efafeac9d8384";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "nu_plugin_regex";
      rev = "aee2bd945f8141fa3be92f34ff1efafeac9d8384";
      fetchSubmodules = false;
      sha256 = "sha256-URomcTJao0Er2JmJNXwOdKMD7jlenhZUt+Rrw+cvB6M=";
    };
    date = "2023-08-02";
  };
  nu_scripts = {
    pname = "nu_scripts";
    version = "83ce76d5f29d45c8c3d35109daa99a962470389b";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "nu_scripts";
      rev = "83ce76d5f29d45c8c3d35109daa99a962470389b";
      fetchSubmodules = false;
      sha256 = "sha256-4BQy+iEOB0dgpbB9AlGJp4mr+vHpch2iE5LTm5RWscs=";
    };
    date = "2023-08-01";
  };
  nushell = {
    pname = "nushell";
    version = "64ed77200758b279a4e4e29f5b0d00b1263f8b01";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "nushell";
      rev = "64ed77200758b279a4e4e29f5b0d00b1263f8b01";
      fetchSubmodules = false;
      sha256 = "sha256-2/Kp3KQhEHN7g2GkzLOc3sv5uG/NLI89fCZAo17x5tQ=";
    };
    date = "2023-08-02";
  };
  pywebscrapbook = {
    pname = "pywebscrapbook";
    version = "7e5068a8254328dada4bca25130ed84eb80ddadd";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "PyWebScrapBook";
      rev = "7e5068a8254328dada4bca25130ed84eb80ddadd";
      fetchSubmodules = false;
      sha256 = "sha256-YNVpz7FmSBftCtS/rwbCtY5Q/ZA2FXSLlmCeT9wnc3I=";
    };
    date = "2023-06-17";
  };
  singlefile-lite = {
    pname = "singlefile-lite";
    version = "ab12a788c4baaa6bc325d2e1a151e17ed463906a";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "singlefile-lite";
      rev = "ab12a788c4baaa6bc325d2e1a151e17ed463906a";
      fetchSubmodules = false;
      sha256 = "sha256-68n5Fyuzzv+0MLOXcAC76SgURo01/QKsPTCIyLu9Q70=";
    };
    date = "2023-08-02";
  };
  terminusdb = {
    pname = "terminusdb";
    version = "9913160a663e0f370886bdbccafa2d6e17a41918";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "terminusdb";
      rev = "9913160a663e0f370886bdbccafa2d6e17a41918";
      fetchSubmodules = false;
      sha256 = "sha256-wr/UXQYXwzQWzqlDBh6mSeKt2Dypcpc62rolwtlSN8c=";
    };
    date = "2023-08-02";
  };
  tg-archive = {
    pname = "tg-archive";
    version = "f8e0cfbbc591405a570365d3af4497bd3125544d";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "tg-archive";
      rev = "f8e0cfbbc591405a570365d3af4497bd3125544d";
      fetchSubmodules = false;
      sha256 = "sha256-8m8E05p5KinqMmWAen2nygBV5daiqWjMwDE29zcNb/A=";
    };
    date = "2023-07-24";
  };
  ublock = {
    pname = "ublock";
    version = "4bd562f3c2b04a460492829beb2a687c116d7571";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "ublock";
      rev = "4bd562f3c2b04a460492829beb2a687c116d7571";
      fetchSubmodules = false;
      sha256 = "sha256-wDzizs23wMFXP64no348BUXRmWvydMoeQap2VGDVuV0=";
    };
    date = "2023-07-31";
  };
  webscrapbook = {
    pname = "webscrapbook";
    version = "c573fff2edb50885d966eeaa91df6cdef83e2fbb";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "webscrapbook";
      rev = "c573fff2edb50885d966eeaa91df6cdef83e2fbb";
      fetchSubmodules = false;
      sha256 = "sha256-CZVRZ2ztZ74jXTR/kfdBwuuisAuKX8Imk/g08rAbj1c=";
    };
    date = "2023-06-21";
  };
}
