# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }: {
  nu_scripts = {
    pname = "nu_scripts";
    version = "3ee56c6ec31fcc8dbffee85e1c73eb6fe0bbba8d";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "nu_scripts";
      rev = "3ee56c6ec31fcc8dbffee85e1c73eb6fe0bbba8d";
      fetchSubmodules = false;
      sha256 = "sha256-luGIvcKOfhDorPfGfL449+eD+58MGo5jMCsNwIRJWt4=";
    };
    date = "2023-07-29";
  };
  pywebscrapbook = {
    pname = "pywebscrapbook";
    version = "7e5068a8254328dada4bca25130ed84eb80ddadd";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "PyWebScrapBook";
      rev = "7e5068a8254328dada4bca25130ed84eb80ddadd";
      fetchSubmodules = false;
      sha256 = "sha256-YNVpz7FmSBftCtS/rwbCtY5Q/ZA2FXSLlmCeT9wnc3I=";
    };
    date = "2023-06-17";
  };
  tg-archive = {
    pname = "tg-archive";
    version = "f8e0cfbbc591405a570365d3af4497bd3125544d";
    src = fetchFromGitHub {
      owner = "cognitive-singularity";
      repo = "tg-archive";
      rev = "f8e0cfbbc591405a570365d3af4497bd3125544d";
      fetchSubmodules = false;
      sha256 = "sha256-8m8E05p5KinqMmWAen2nygBV5daiqWjMwDE29zcNb/A=";
    };
    date = "2023-07-24";
  };
}
