name: ci

on:
  push:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v22
        with:
            nix_conf: |
              experimental-features = nix-command flakes
              access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run checks
        run: nix flake check

      - name: Check formatting
        run: nix develop --no-update-lock-file --command treefmt
