name: ci
on:
  push:
    branches:
      - main
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: cognitive-singularity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run checks
        run: nix flake check
      - name: Check formatting
        run: nix develop --no-update-lock-file --command treefmt
